services:
  web:
    build: ./
    env_file:
      - ./.env
    environment:
      - BASE_DIR=/usr/src/app
    volumes:
      - ./:/usr/src/app
      - static_volume:/usr/src/app/static
      - certs_volume:/usr/src/app/certs
      - logs_volume:/user/src/app/logs
      - backups_volume:/user/src/app/backups
      - instance_volume:/user/src/app/instance
      - ./instance/configuration.py:/usr/src/app/instance/configuration.py
      - ./uwsgi.ini.template:/etc/uwsgi/uwsgi.ini.template  # Mount the template
    expose:
      - 8888
    depends_on:
      - "db"
      - "redis"
    restart: always
  db:
    image: postgres:16-bullseye
    restart: always
    env_file:
      - ./.env.db
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
    volumes:
      - blockpy_db:/var/lib/postgresql/data/
      - ./conf/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.4-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - "6379:6379"
    command: sh -c 'redis-server --requirepass "$$REDIS_PASSWORD"'
  huey:
    build: ./
    command: /usr/src/app/venv/bin/python3 manage.py huey
    user: www-data
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - logs_volume:/user/src/app/logs
      - instance_volume:/user/src/app/instance
      - static_volume:/usr/src/app/static
      - certs_volume:/usr/src/app/certs
      - ./instance/configuration.py:/usr/src/app/instance/configuration.py
    depends_on:
      - "redis"
    env_file:
      - ./.env
  nginx:
    image: nginx:1.27-alpine
    env_file:
      - ./.env
    volumes:
      - ./conf/nginx/nginx.conf.template:/etc/nginx/nginx.conf.template
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    command: rm -f /etc/nginx/conf.d/default.conf && /bin/bash -c "envsubst '\$SERVER_NAME' < /etc/nginx/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    restart: always
# Names our volume
volumes:
  blockpy_db:
  static_volume:
  certs_volume:
  logs_volume:
  backups_volume:
  instance_volume: